version: '3'
services:
  internal_db:
    image: postgres:16.0
    container_name: internal-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 562bb3889e26d8fe
      POSTGRES_DB: gomyadmin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - test-network
  internal_cache:
    image: redis:7.2
    container_name: internal-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass 42ppjaM7R0ji+AAER3ZrTdzyIxE=
    networks:
      - test-network
  test_database:
    image: postgres:16.0
    container_name: test-database
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4c9642ea7580a191
      POSTGRES_DB: holaaa
    networks:
      - test-network
volumes:
  postgres-data:
networks:
  test-network:

    